version: "3"

services:
    website:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        image: website-nextjs
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
# networks:
#     default:
#         external:
#             name: nginx-proxy-example
