version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    environment:
      - VIRTUAL_HOST=site2.com
      - LETSENCRYPT_HOST=site2.com
      - LETSENCRYPT_EMAIL=email@site2.com
    volumes:
      - .:/etc/nginx/conf.d
networks:
  default:
    external:
      name: nginx-proxy-example
