version: "3"

services:
    website:
        container_name: website
        build:
            context: .
            dockerfile: Dockerfile
        image: website-nginx-nextjs

        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - .:/app

networks:
    default:
        external:
            name: nginx-proxy-example
